services:
  backend:
    environment:
      - WORDPRESS_DB_HOST=127.0.0.1
      - WORDPRESS_SITE_URL=${WORDPRESS_SITE_URL}
    ports:
      - "8080:80"
    restart: unless-stopped
  frontend:
    build:
      target: prod
    volumes:
      - /app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_WORDPRESS_URL=${WORDPRESS_SITE_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
