name: Deploy to Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Preflight connectivity (debug)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          command_timeout: 2m
          script_stop: true
          script: |
            set -x
            echo "Testing TCP connectivity and auth to $HOSTNAME"
            echo ok

      - name: Upload project to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          debug: true
          source: "."
          target: ${{ secrets.DEPLOY_PROJECT_DIR }}
          overwrite: true
          rm: false
          strip_components: 0
          timeout: 600s

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            PROJECT_DIR=${{ secrets.DEPLOY_PROJECT_DIR }}
            mkdir -p "$PROJECT_DIR"
            cd "$PROJECT_DIR"

            # Write fresh .env from secret (single source of truth)
            if [ -n "${{ secrets.DEPLOY_ENV_FILE }}" ]; then
              printf "%s" "${{ secrets.DEPLOY_ENV_FILE }}" > .env
            fi

            # Build and (re)start services with prod overrides
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

            # Optional: cleanup dangling images
            docker image prune -f || true


